//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AqaratProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public string LstType { get; set; }
        public string section { get; set; }
        public string Location { get; set; }
        public string lstView { get; set; }
        public int conDate { get; set; }
        public string FinishingType { get; set; }
        public int price { get; set; }
        public int num_of_rooms { get; set; }
        public int num_of_floors { get; set; }
        public int num_of_bathroom { get; set; }
        public int size { get; set; }
        public string address { get; set; }
        public string property_image { get; set; }
        public int id { get; set; }
        public int user_id { get; set; }
    
        public virtual user user { get; set; }
    }
}
